services:
  ssmats_au_db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: ssmats_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ssmats_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  ssmats_au_redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  backend_ssmats_au:
    build: 
      context: ./backend 
      dockerfile: ../docker/productions/backend/Dockerfile 
    container_name: backend_ssmats_au
    restart: unless-stopped
    # ports:
    #   - "3000:3000"
    depends_on:
      ssmats_au_db:
        condition: service_healthy
      ssmats_au_redis:
        condition: service_started
    environment:
      DB_HOST: ssmats_au_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_NAME: ssmats_db
      DATABASE_URL: postgresql://postgres:postgres123@ssmats_au_db:5432/ssmats_db
      REDIS_HOST: ssmats_au_redis
      REDIS_PORT: 6379

  admin_au:
    build: 
      context: ./admin
      dockerfile: ../docker/productions/admin/Dockerfile
    container_name: admin_au
    restart: unless-stopped
    # ports:
    #   - "4000:4000"
    # command: bun dev
    # volumes:
    #   - ./admin:/app
    #   - /app/node_modules
    depends_on:
      - backend_ssmats_au
    environment:
      - VITE_API_BASE_URL=/api

  nginx:
    build:
      context: .
      dockerfile: docker/productions/nginx/Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - admin_au
      - backend_ssmats_au

volumes:
  postgres_data:
  redis_data: